<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DentalClinic.DomainService\DentalClinic.DomainService.csproj" />
    <ProjectReference Include="..\DentalClinic.Dto\DentalClinic.Dto.csproj" />
    <ProjectReference Include="..\DentalClinic.Infrastructure\DentalClinic.Infrastructure.csproj" />
  </ItemGroup>
</Project>