<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DentalClinic.Dto\DentalClinic.Dto.csproj" />
    <ProjectReference Include="..\DentalClinic.Facade\DentalClinic.Facade.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mappers\" />
    <Folder Include="Models\" />
    <Folder Include="Models\Requests\" />
    <Folder Include="Models\Responses\" />
  </ItemGroup>

</Project>
